import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';

/**
 * Echoes the request ID generated by pino-http back to the client as
 * X-Request-Id response header.
 *
 * pino-http sets req.id on every request (honouring an incoming X-Request-Id
 * header or generating a fresh UUID via genReqId in logger.config.ts).
 * This middleware copies that value to the response so clients and upstream
 * gateways can correlate logs with individual requests.
 *
 * Must be registered AFTER LoggerModule so pino-http has already set req.id.
 */
@Injectable()
export class RequestIdMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction) {
    const requestId = (req as any).id as string | undefined;
    if (requestId) {
      res.setHeader('X-Request-Id', requestId);
    }
    next();
  }
}
